(()=>{'use strict';
const KEY='mylife-v1-data'; const $=s=>document.querySelector(s); const app=$('#app'),overlay=$('#overlay'),sheet=$('#sheet');
const today=()=>new Date().toISOString().slice(0,10), id=()=>Date.now()+Math.floor(Math.random()*1000), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let data={plans:[],pool:[],life:[],moods:[],anniv:[],habits:[],routines:[]};try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')data={...data,...x}}catch(e){};
let page='today', month=new Date(new Date().getFullYear(),new Date().getMonth(),1), selected=today(), archiveMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1300)}
function open(html){sheet.innerHTML=html;overlay.classList.remove('hidden')} function close(){overlay.classList.add('hidden');sheet.innerHTML=''} overlay.addEventListener('click',e=>{if(e.target===overlay)close()});
function header(title,sub,back=false,plus=''){return `<div class="top"><button class="icon" data-act="${back?'today':'space'}">${back?'‹':'☰'}</button><button class="icon" ${plus?`data-act="${plus}"`:''}>${plus?'＋':'⋯'}</button></div><h1 class="title">${title}</h1><div class="sub">${sub}</div>`}
function rows(items,empty,fn){return items.length?items.map(fn).join(''):`<div class="empty">${empty}</div>`}
function render(){document.querySelectorAll('#nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); if(page==='today')renderToday();else if(page==='plan')renderPlan();else if(page==='life')renderLife();else renderArchive()}
function renderToday(){const ps=data.plans.filter(p=>p.start<=today()&&p.end>=today()), mood=data.moods.filter(m=>m.date===today()).at(-1);app.innerHTML=`<section class="page">${header('Today',new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}))}<div class="section"><div class="label"><span>MY DAY</span><span>今天</span></div><div class="card">${rows(data.routines,'今天还没有 Routine。',r=>`<div class="row"><div><b>${esc(r.title)}</b><div class="muted">${esc(r.time||'未设时间')}</div></div><button class="btn" data-act="routine">打开</button></div>`)}</div></div><div class="section"><div class="label"><span>今日计划</span><span>${ps.length}</span></div><div class="card">${rows(ps,'今天还没有计划。',p=>planRow(p))}</div></div><div class="section"><div class="label"><span>HABIT</span><span>今天</span></div><div class="card">${rows(data.habits,'今天还没有习惯。',h=>`<div class="row"><b>${esc(h.title)}</b><button class="btn" data-act="habit">打卡</button></div>`)}</div></div><div class="section"><div class="label"><span>MOOD</span><span>今日代表心情</span></div><div class="card row"><div><b>${mood?mood.emoji+' '+esc(mood.label):'还没记录'}</b><div class="muted">可随时修改</div></div><button class="btn" data-act="mood">打卡</button></div></div><div class="section"><div class="label"><span>轻提醒</span></div><div class="card">${annivReminder()}</div></div></section>`}
function planRow(p){return `<div class="row"><div style="display:flex;gap:10px;align-items:center"><button class="check ${p.done?'done':''}" data-toggle="${p.id}"></button><div><b>${esc(p.title)}</b><div class="muted">${p.start}${p.end!==p.start?' → '+p.end:''}</div></div></div><button class="btn" data-editplan="${p.id}">编辑</button></div>`}
function renderPlan(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let c=['日','一','二','三','四','五','六'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<first;i++)c+='<div></div>';for(let n=1;n<=days;n++){const d=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,ps=data.plans.filter(p=>p.start<=d&&p.end>=d);c+=`<button class="day ${d===selected?'sel':''} ${d===today()?'today':''}" data-date="${d}"><span class="num">${n}</span>${ps.slice(0,3).map(p=>`<span class="event">${esc(p.title)}</span>`).join('')}${ps.length>3?`<span class="muted">+${ps.length-3}</span>`:''}</button>`}const chosen=data.plans.filter(p=>p.start<=selected&&p.end>=selected);app.innerHTML=`<section class="page">${header('Plan','月视图 · 计划 · Plan Pool · 纪念日',false,'addplan')}<div class="card"><div class="row"><button class="icon" data-month="-1">‹</button><b>${y}年${m+1}月</b><button class="icon" data-month="1">›</button></div><div class="cal">${c}</div></div><div class="section"><div class="label"><span>${selected}</span><span>所选日期</span></div><div class="card">${rows(chosen,'这一天没有计划。',planRow)}</div></div><div class="section"><div class="label"><span>PLAN POOL</span><button class="btn" data-act="addpool">＋</button></div><div class="card">${rows(data.pool,'Plan Pool 还是空的。',p=>`<div class="row"><b>${esc(p.title)}</b><div><button class="btn" data-pooldate="${p.id}">安排</button> <button class="btn" data-delpool="${p.id}">删除</button></div></div>`)}</div></div><div class="section"><div class="label"><span>ANNIVERSARY</span><button class="btn" data-act="anniv">＋</button></div><div class="card">${rows(data.anniv,'还没有纪念日。',a=>`<div class="row"><div><b>♡ ${esc(a.title)}</b><div class="muted">${a.date}</div></div><button class="btn" data-delanniv="${a.id}">删除</button></div>`)}</div></div></section>`}
function renderLife(){const ls=[...data.life].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));app.innerHTML=`<section class="page">${header('Life','私人生活流 · 文字 · 照片 · 地点 · 标签',false,'addlife')}<div class="card">${rows(ls,'还没有生活记录。',x=>`<div class="row"><div><b>${esc(x.text||'生活记录')}</b><div class="muted">${x.date} ${x.time||''}${x.location?' · '+esc(x.location):''}</div>${x.tags?`<div class="muted">#${esc(x.tags)}</div>`:''}</div><button class="btn" data-dellife="${x.id}">删除</button></div>`)}</div></section>`}
function renderArchive(){const y=archiveMonth.getFullYear(),m=archiveMonth.getMonth(),ym=`${y}-${String(m+1).padStart(2,'0')}`,ls=data.life.filter(x=>x.date.startsWith(ym)),ps=data.plans.filter(x=>x.start.startsWith(ym)||x.end.startsWith(ym)),ms=data.moods.filter(x=>x.date.startsWith(ym));app.innerHTML=`<section class="page">${header('Archive','按月回顾 · 从原始记录读取')}<div class="card row"><button class="icon" data-arch="-1">‹</button><b>${y}年${m+1}月</b><button class="icon" data-arch="1">›</button></div><div class="section"><div class="statgrid"><div class="stat"><span class="muted">Life</span><strong>${ls.length}</strong></div><div class="stat"><span class="muted">Plan</span><strong>${ps.length}</strong></div><div class="stat"><span class="muted">Mood</span><strong>${ms.length}</strong></div><div class="stat"><span class="muted">完成计划</span><strong>${ps.filter(x=>x.done).length}</strong></div></div></div><div class="section"><div class="label"><span>这个月的我</span></div><div class="card">${rows(ls,'这个月还没有 Life 记录。',x=>`<div class="row"><div><b>${esc(x.text||'生活记录')}</b><div class="muted">${x.date}</div></div></div>`)}</div></div></section>`}
function annivReminder(){const md=today().slice(5);const a=data.anniv.filter(x=>x.date.slice(5)===md);return a.length?a.map(x=>`<div class="row"><b>♡ ${esc(x.title)}</b><span class="pill">今天</span></div>`).join(''):'<div class="empty">今天没有额外提醒。</div>'}
function formHead(t){return `<div class="sheethead"><h2>${t}</h2><button class="icon" data-close>×</button></div>`}
function planForm(pid){const p=data.plans.find(x=>x.id===pid)||{title:'',start:selected,end:selected};open(`${formHead(pid?'编辑计划':'新建计划')}<form id="planForm"><div class="field"><label>计划</label><input name="title" required value="${esc(p.title)}"></div><div class="two"><div class="field"><label>开始日期</label><input type="date" name="start" required value="${p.start}"></div><div class="field"><label>结束日期</label><input type="date" name="end" required value="${p.end}"></div></div><button class="primary">保存</button>${pid?`<div style="height:9px"></div><button type="button" class="danger" data-delplan="${pid}">删除计划</button>`:''}</form>`);$('#planForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),obj={id:pid||id(),title:f.get('title').trim(),start:f.get('start'),end:f.get('end'),done:p.done||false};if(obj.end<obj.start)obj.end=obj.start;if(pid)data.plans=data.plans.map(x=>x.id===pid?obj:x);else data.plans.push(obj);save();close();render();toast('已保存')}}
function quick(){open(`${formHead('快速记录')}<div class="spacegrid"><button class="space" data-act="addplan">▣<b>计划</b></button><button class="space" data-act="addlife">○<b>Life</b></button><button class="space" data-act="mood">☺<b>心情</b></button><button class="space" data-act="anniv">♡<b>纪念日</b></button></div>`)}
function space(){open(`${formHead('My Space')}<div class="spacegrid"><button class="space" data-act="habit">🌱<b>Habit</b></button><button class="space" data-act="routine">↻<b>Routine</b></button><button class="space" data-act="money">¥<b>Money</b></button><button class="space" data-act="health">♡<b>Health</b></button><button class="space" data-act="knowledge">▤<b>Knowledge</b></button><button class="space" data-act="backup">⚙<b>Settings</b></button></div>`)}
function simpleModule(name,text){open(`${formHead(name)}<div class="card"><div class="row"><b>${name}</b><span class="pill">入口正常</span></div><p class="muted">${text}</p></div>`)}
function mood(){open(`${formHead('Mood')}<div class="spacegrid">${[['😄','开心'],['🙂','不错'],['😐','一般'],['😔','低落'],['😤','烦躁'],['🥱','疲惫']].map(x=>`<button class="space" data-mood="${x[0]}|${x[1]}">${x[0]}<b>${x[1]}</b></button>`).join('')}</div>`)}
function anniv(){open(`${formHead('新建纪念日')}<form id="annivForm"><div class="field"><label>名称</label><input name="title" required></div><div class="field"><label>日期</label><input name="date" type="date" required value="${today()}"></div><button class="primary">保存</button></form>`);$('#annivForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.anniv.push({id:id(),title:f.get('title').trim(),date:f.get('date')});save();close();render();toast('纪念日已保存')}}
function lifeForm(){open(`${formHead('记录 Life')}<form id="lifeForm"><div class="field"><label>记录</label><textarea name="text" required></textarea></div><div class="two"><div class="field"><label>日期</label><input type="date" name="date" value="${today()}"></div><div class="field"><label>时间</label><input type="time" name="time"></div></div><div class="field"><label>地点</label><input name="location"></div><div class="field"><label>标签</label><input name="tags" placeholder="例如：日常,朋友"></div><button class="primary">保存</button></form>`);$('#lifeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.life.push({id:id(),text:f.get('text').trim(),date:f.get('date'),time:f.get('time'),location:f.get('location'),tags:f.get('tags')});save();close();render();toast('已记录')}}
function poolForm(){open(`${formHead('加入 Plan Pool')}<form id="poolForm"><div class="field"><label>计划</label><input name="title" required></div><button class="primary">保存</button></form>`);$('#poolForm').onsubmit=e=>{e.preventDefault();data.pool.push({id:id(),title:new FormData(e.target).get('title').trim()});save();close();render()}}
function backup(){open(`${formHead('Settings & Backup')}<div class="card"><div class="row"><span>版本</span><b>v1.0 Clean</b></div><div class="row"><span>数据</span><span class="muted">Local First</span></div></div><div style="height:12px"></div><button class="danger" data-reset>清空 v1.0 测试数据</button>`)}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.page){page=t.dataset.page;render();return}if(t.id==='quickBtn'){quick();return}if(t.dataset.close!==undefined){close();return}if(t.dataset.date){selected=t.dataset.date;render();return}if(t.dataset.month){month=new Date(month.getFullYear(),month.getMonth()+Number(t.dataset.month),1);render();return}if(t.dataset.arch){archiveMonth=new Date(archiveMonth.getFullYear(),archiveMonth.getMonth()+Number(t.dataset.arch),1);render();return}if(t.dataset.toggle){const p=data.plans.find(x=>x.id==t.dataset.toggle);if(p){p.done=!p.done;save();render()}return}if(t.dataset.editplan){planForm(Number(t.dataset.editplan));return}if(t.dataset.delplan){data.plans=data.plans.filter(x=>x.id!=t.dataset.delplan);save();close();render();return}if(t.dataset.dellife){data.life=data.life.filter(x=>x.id!=t.dataset.dellife);save();render();return}if(t.dataset.delpool){data.pool=data.pool.filter(x=>x.id!=t.dataset.delpool);save();render();return}if(t.dataset.delanniv){data.anniv=data.anniv.filter(x=>x.id!=t.dataset.delanniv);save();render();return}if(t.dataset.pooldate){const p=data.pool.find(x=>x.id==t.dataset.pooldate);if(p){data.plans.push({id:id(),title:p.title,start:selected,end:selected,done:false});data.pool=data.pool.filter(x=>x.id!=p.id);save();render();toast('已安排到 '+selected)}return}if(t.dataset.mood){const [emoji,label]=t.dataset.mood.split('|');data.moods=data.moods.filter(x=>x.date!==today());data.moods.push({id:id(),date:today(),emoji,label});save();close();render();toast('心情已打卡');return}if(t.dataset.reset!==undefined){if(confirm('确定清空 v1.0 测试数据？')){localStorage.removeItem(KEY);location.reload()}return}const a=t.dataset.act;if(!a)return;if(a==='space')space();else if(a==='today'){page='today';close();render()}else if(a==='addplan'){close();planForm()}else if(a==='addlife'){close();lifeForm()}else if(a==='addpool'){poolForm()}else if(a==='mood')mood();else if(a==='anniv')anniv();else if(a==='habit')simpleModule('Habit','下一阶段接入打卡类型、周期、次数与热力图。');else if(a==='routine')simpleModule('Routine','下一阶段接入时间、步骤、增删与 Habit 联动。');else if(a==='money')simpleModule('Money','下一阶段接入分类、预算、小票与月度总结。');else if(a==='health')simpleModule('Health','下一阶段接入体重、生理期、运动、睡眠、步数与趋势图。');else if(a==='knowledge')simpleModule('Knowledge','下一阶段接入笔记、标签与照片上传。');else if(a==='backup')backup()});
// Deliberately unregister every old service worker/cache. v1.0 uses no SW until stability is verified.
if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{})}if('caches'in window){caches.keys().then(ks=>Promise.all(ks.map(k=>caches.delete(k)))).catch(()=>{})}
render();
})();
